#!/bin/bash
set -e

# Set some initial variables
gitdir=$(git rev-parse --git-dir)
sha=0
previous_sha=0

# Check usage
if [ $# -lt 1 ]; then
    echo "Usage: git-draw-watch <git-draw command> <git-draw options>"
    exit $1
fi

# Kill all child processes on exit
trap "kill -- -$BASHPID" EXIT

# Re-run command if the git file system has changed
while true; do
    sha=`ls -lR $gitdir | sha1sum`
    if [ "$sha" != "$previous_sha" ]; then 
        echo "--> Files changed, running $@"

        # Kill subprocesses (should add a command line option to select whether to do this)
        #if [ "x$previous_sha" != "x0" ]; then
        #    echo "$(jobs -p)"
        #    pkill -TERM -P $(jobs -p)
        #fi

        # Remember the new sha and run the input commands
        previous_sha=$sha
        $@ &
    fi
    sleep 1
done
